export const themes = [
  { title: 'Constitutional Law, Governance and Institutional Accountability', desc: 'Examine constitutional principles, public institutions and the exercise of state power.', icon: '§', topics: ['Legislative, executive and judicial accountability', 'Federalism and Centre–State relations', 'Fundamental rights in the digital environment', 'Judicial review and administrative discretion', 'Transparency, public participation and reasoned decision-making'] },
  { title: 'Legislative Reform, Public Policy and Regulatory Effectiveness', desc: 'Study how laws and policies are designed, implemented and evaluated.', icon: '↗', topics: ['Gaps, inconsistencies and overlaps in legislation', 'Public consultation and evidence-based lawmaking', 'Regulatory impact assessment and compliance burdens', 'Barriers to implementing public policies', 'Evaluation of legal reforms and institutional outcomes'] },
  { title: 'Artificial Intelligence, Emerging Technologies and Ethics', desc: 'Explore legal, ethical and governance questions arising from AI and technological change.', icon: '⌘', topics: ['Accountability for AI-assisted decisions', 'Algorithmic bias, transparency and human oversight', 'Generative AI, misinformation and synthetic media', 'AI in courts, public administration and legal practice', 'Governance of autonomous systems'] },
  { title: 'Data Protection, Privacy and Digital Rights', desc: 'Investigate how digital systems shape privacy, autonomy and individual rights.', icon: '◉', topics: ['Consent and grounds for personal-data processing', 'Children’s privacy and age-appropriate digital services', 'Workplace monitoring, biometrics and surveillance', 'Cross-border data transfers', 'Privacy in healthcare, education and public services'] },
  { title: 'Cybersecurity, Cybercrime and Digital Evidence', desc: 'Consider legal responses to cyber threats, digital offences and electronic evidence.', icon: '⌁', topics: ['Cyber fraud and digital-intermediary responsibilities', 'Incident reporting and organisational accountability', 'Digital evidence, authenticity and chain of custody', 'Cybercrime investigation and cross-border cooperation', 'Cybersecurity duties for critical infrastructure'] },
  { title: 'Intellectual Property, Innovation and Technology Transfer', desc: 'Study innovation, licensing and the public-interest dimensions of intellectual property.', icon: '✳', topics: ['AI-assisted inventions and creative works', 'Patent quality, examination and technology access', 'Copyright and digital content', 'Trade secrets and confidential know-how', 'Licensing and university–industry collaboration'] },
  { title: 'Corporate Governance, Mergers and Acquisitions, and Business Regulation', desc: 'Explore corporate duties, M&A, investment and emerging commercial questions.', icon: '▤', topics: ['Directors’ duties and shareholder protection', 'Investment rights, dilution and corporate control', 'Legal due diligence and risk allocation in M&A', 'Start-up governance and corporate restructuring', 'Responsible business conduct and compliance'] },
  { title: 'Competition Law, Digital Markets and Consumer Protection', desc: 'Explore market power, fair competition and consumer interests in digital markets.', icon: '⇄', topics: ['Platform dominance and market access', 'Data advantages and barriers to competition', 'Algorithmic pricing and coordinated behaviour', 'Dark patterns and online consumer protection', 'Merger assessment in technology-driven markets'] },
  { title: 'Litigation, Judicial Administration and Access to Justice', desc: 'Examine the accessibility, effectiveness and fairness of judicial processes.', icon: '⚖', topics: ['Case management, procedural delay and court administration', 'Technology-enabled courts and digital exclusion', 'Legal aid and affordable representation', 'Commercial litigation and enforcement of judgments', 'Accessibility of justice for underserved groups'] },
  { title: 'Arbitration, Mediation and Other Forms of ADR', desc: 'Study the design and effectiveness of dispute-resolution mechanisms.', icon: '↔', topics: ['Independence and impartiality in arbitration', 'Institutional and ad hoc arbitration', 'Enforcement and challenges to arbitral awards', 'Mediation and online dispute resolution', 'Confidentiality, costs and access'] },
  { title: 'Criminal Justice, Evidence and Procedural Safeguards', desc: 'Assess criminal justice with attention to effective enforcement and individual rights.', icon: '◈', topics: ['Investigation standards and procedural fairness', 'Bail, pre-trial detention and timely adjudication', 'Victim participation and witness protection', 'Forensic evidence and emerging technologies', 'Sentencing, rehabilitation and alternatives to imprisonment'] },
  { title: 'Environment, Public Health and Social Welfare', desc: 'Explore legal and policy responses to shared social and environmental challenges.', icon: '⌂', topics: ['Environmental accountability and climate governance', 'Public-health regulation and healthcare access', 'Biotechnology law and ethics', 'Labour rights and platform-based work', 'Disability rights and social-welfare implementation'] },
];

export const programs = [
  { slug: 'short-term', name: 'Short-Term Program', duration: '4–6 months', description: 'A focused question, specific legal issue or narrowly defined comparative study.', number: '01' },
  { slug: 'mid-term', name: 'Mid-Term Program', duration: '6–8 months', description: 'A broader inquiry involving detailed doctrinal analysis, comparative research or limited stakeholder engagement.', number: '02' },
  { slug: 'long-term', name: 'Long-Term Program', duration: '12–18 months', description: 'A complex investigation requiring extensive analysis, empirical work or substantial policy recommendations.', number: '03' },
];

export const committee = [
  { name: 'Dr. S. K. Murthy', role: 'Board member · profile supplied for confirmation', image: '', bio: 'Brings experience in teaching, research and development, and intellectual property. His work spans patent practice, data protection, corporate governance and standards policy.' },
  { name: 'Mr. Ananth Sripadarao', role: 'Board member · profile supplied for confirmation', image: '', bio: 'Brings experience in intellectual property law and legal affairs across Asia-Pacific, the Middle East and Africa, including patents, technology licensing, corporate governance and M&A.' },
];

export const publications = [
  { title: 'Research programme publications are in preparation', type: 'Institutional update', description: 'Research outputs will be listed here after completion and editorial review, with author details and access information.', year: 'Coming soon' },
];

export const newsItems = [
  { title: 'Research programme announcements will appear here', type: 'Announcement', date: 'Updates forthcoming', description: 'Application windows, eligibility requirements and submission instructions will be published when confirmed.' },
];
